# Generated by Django 5.2.5 on 2025-08-08 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("paystack_id", models.BigIntegerField(unique=True)),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=10)),
                (
                    "gateway_response",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paid_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("channel", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("product_id", models.UUIDField()),
                ("user_id", models.PositiveIntegerField()),
                ("order_number", models.CharField(max_length=20)),
                ("fees", models.PositiveIntegerField()),
                ("card_type", models.CharField(blank=True, max_length=50, null=True)),
                ("last4", models.CharField(blank=True, max_length=4, null=True)),
                ("bank", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("customer_code", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transaction",
                "db_table": "transaction",
                "ordering": ["-created_on"],
            },
        ),
    ]
